/* eslint-disable react/jsx-filename-extension */
import React from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import "../styles/globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({
  weight: ["400", "500", "600", "700", "900"],
  display: "swap",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: 'Portal RH',
  description: 'Generated by Paiper',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <ToastContainer />
        {children}
      </body>
    </html>
  )
}